SELECT
    CAST(raceid AS integer) AS race_id,
    CAST(year AS integer) AS season_year,
    CAST(round AS integer) AS season_round,
    CAST(circuitid AS integer) AS circuit_id,
    CAST(name AS varchar) AS race_name,
    CAST(date AS date) AS race_date,
    CAST(NULLIF(time, '\N') AS time) AS race_time_utc,
    CAST(url AS varchar) AS race_url,
    CAST(NULLIF(fp1_date, '\N') AS date) AS fp1_date,
    CAST(NULLIF(fp1_time, '\N') AS time) AS fp1_time_utc,
    CAST(NULLIF(fp2_date, '\N') AS date) AS fp2_date,
    CAST(NULLIF(fp2_time, '\N') AS time) AS fp2_time_utc,
    CAST(NULLIF(fp3_date, '\N') AS date) AS fp3_date,
    CAST(NULLIF(fp3_time, '\N') AS time) AS fp3_time_utc,
    CAST(NULLIF(quali_date, '\N') AS date) AS qualifying_date,
    CAST(NULLIF(quali_time, '\N') AS time) AS qualifying_time_utc,
    CAST(NULLIF(sprint_date, '\N') AS date) AS sprint_date,
    CAST(NULLIF(sprint_time, '\N') AS time) AS sprint_time_utc
FROM {{ source('f1', 'races') }}
